version: '3'
services:
  web:
    environment:
      NODE_CONFIG: '{"sitetitle": "maidavale.org",
                     "sitesubtitle": "Another tech blog"}'
  #     DB_USER: notesyolo
  #     DB_PASSWORD: cheese
  #     DB_DATABASE: notes12
  # database:
  #   environment:
  #      POSTGRES_USER: notesyolo
  #      POSTGRES_PASSWORD: cheese
  #      POSTGRES_DB: notes12
