version: '3'
services:
  web:
    build: .
    entrypoint: ["npm", "run", "dev"]
    environment:
      NODE_ENV: development
    volumes:
      - .:/usr/src/app
  database:
    ports:
     - "5432:5432"
